In [13]:
import numpy as np
import copy

In [14]:
# regression equation :-  Y = θ0 + θ1 * X
X = [[1,1], [1,2], [1,3], [1,4], [1,5]]
Y = [2,4,6,8,10]

In [15]:
#theta actual values should be 0 and 2
theta = [2,2]

In [16]:
alpha = 0.01

In [17]:
X = np.array(X)
print(X)

[[1 1]
 [1 2]
 [1 3]
 [1 4]
 [1 5]]


In [18]:
X = np.transpose(X)
print(X)

[[1 1 1 1 1]
 [1 2 3 4 5]]


In [19]:
Y = np.array(Y)
print(Y)

[ 2  4  6  8 10]


In [20]:
theta = np.array(theta)
print(theta)

[2 2]


In [21]:
theta_new = np.zeros([2])
print(theta_new)

[0. 0.]


In [22]:
for i in range(1000):
    Y_pred = np.dot(theta, X)
    error = Y_pred - Y
    for j in range(len(theta)):
        theta_new[j] = theta[j] - alpha*np.dot(error, X[j,:])
    theta= copy.deepcopy(theta_new)

In [23]:
print(Y_pred)

[2.00027882 4.00017201 6.00006519 7.99995838 9.99985156]


In [24]:
print(theta) # = [0 2]

[3.82377690e-04 1.99989409e+00]
