In [21]:
import numpy as np
import copy

In [22]:
# classification equation :-  Y = θ0 + θ1 * X 
X_train = [[1,1,1,1,1], [1,2,3,4,5]]
Y_train = [0,0,0,1,1]

In [23]:
alpha = 0.01

In [24]:
#theta actual values should be 0 and 2
theta = [2,2]

In [25]:
X_train = np.array(X_train)
print(X_train)

[[1 1 1 1 1]
 [1 2 3 4 5]]


In [26]:
X = np.transpose(X)
print(X)

[[1 1 1 1 1]
 [1 2 3 4 5]]


In [27]:
Y_train = np.array(Y_train)
print(Y_train)

[0 0 0 1 1]


In [28]:
theta = np.array(theta)
print(theta)

[2 2]


In [29]:
theta_new = np.zeros([2])
print(theta_new)

[0. 0.]


In [30]:
for i in range(1000):
    Y_pred = np.dot(theta, X_train)
    Y_pred = 1/(1+np.exp(-Y_train))
    error = Y_pred - Y_train
    for j in range(len(theta)):
        theta_new[j] = theta[j]-alpha*np.dot(error, X_train[j,:])
    theta= copy.deepcopy(theta_new)

In [31]:
print(Y_pred)

[0.5        0.5        0.5        0.73105858 0.73105858]
