In [79]:
import torch

In [3]:
x=torch.empty(4)

In [4]:
x

tensor([0., 0., 0., 0.])

In [7]:
y = torch.empty(2,3,4)

In [8]:
y

tensor([[[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 1.7591e+22, 7.7052e+31, 7.2148e+22],
         [2.5226e-18, 4.1488e-08, 1.0356e-11, 3.0883e-09]],

        [[1.0374e-08, 4.2107e-11, 2.6659e-09, 2.9572e-18],
         [6.7333e+22, 1.7591e+22, 1.7184e+25, 4.3222e+27],
         [6.1972e-04, 7.2443e+22, 1.7728e+28, 7.0367e+22]]])

In [9]:
z=torch.zeros(3)

In [10]:
z

tensor([0., 0., 0.])

In [11]:
c=torch.ones(2)

In [12]:
c

tensor([1., 1.])

In [13]:
f=torch.rand(3)

In [14]:
f

tensor([0.0032, 0.6020, 0.8962])

In [15]:
s=torch.ones(2,3,dtype=torch.int)

In [16]:
s

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [17]:
x=torch.ones(3)

In [18]:
y=torch.ones(3)

In [19]:
x+y

tensor([2., 2., 2.])

In [20]:
y-x

tensor([0., 0., 0.])

In [21]:
y/x

tensor([1., 1., 1.])

In [22]:
torch.add(x,y)

tensor([2., 2., 2.])

In [23]:
torch.sub(x,y)

tensor([0., 0., 0.])

# in place operation

In [24]:
y.add_(x)

tensor([2., 2., 2.])

In [25]:
y

tensor([2., 2., 2.])

In [26]:
x

tensor([1., 1., 1.])

In [27]:
t=torch.rand(2,3)

In [28]:
t

tensor([[0.7863, 0.4797, 0.2784],
        [0.6259, 0.3116, 0.4490]])

In [29]:
t[0,0]

tensor(0.7863)

# slicing or scaling

In [33]:
t[:,0]

tensor([0.7863, 0.6259])

In [34]:
t[0,:]

tensor([0.7863, 0.4797, 0.2784])

In [40]:
r=t.view(-1) #1D 

In [42]:
r

tensor([0.7863, 0.4797, 0.2784, 0.6259, 0.3116, 0.4490])

In [36]:
i=t.view(-1) #1D 

In [37]:
i

tensor([0.7863, 0.4797, 0.2784, 0.6259, 0.3116, 0.4490])

In [38]:
u=t.view(-1,2) #two columns

In [39]:
u

tensor([[0.7863, 0.4797],
        [0.2784, 0.6259],
        [0.3116, 0.4490]])

In [44]:
import numpy as np

In [45]:
a=torch.ones(3)

In [46]:
a

tensor([1., 1., 1.])

In [47]:
b=a.numpy()

In [48]:
b

array([1., 1., 1.], dtype=float32)

In [49]:
c=torch.from_numpy(b)

In [50]:
c

tensor([1., 1., 1.])

# autograd

In [51]:
x=torch.ones(1,requires_grad=True)

In [52]:
y=x**2

In [53]:
z=3*y

In [54]:
z.backward()

In [55]:
x.grad

tensor([6.])

In [56]:
print(z)

tensor([3.], grad_fn=<MulBackward0>)


# gradient decsent

In [62]:
x=torch.tensor(1.0)
y=torch.tensor(2.0)

theta=torch.tensor(1.0, requires_grad=True)

y_pred= theta*x

J= (y_pred-y)**2

J.backward()

theta.grad

tensor(-2.)

In [63]:
x=torch.tensor(1.0)
y=torch.tensor(2.0)

theta=torch.tensor(1.0, requires_grad=True)

y_pred= theta*x

J= (y_pred-y)**2

J.backward()
theta.grad

theta.grad.zero_()

J.backward()
theta.grad

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [73]:
x=np.array([1.0,2.0,3.0,4.0])
y=np.array([2.0,4.0,6.0,8.0])

theta=0.0

#1 epoch=1 forward and 1 backward
def forward(x,theta):
    return theta*x

def gradient(x,y,y_pred):
    return np.dot((2.0*x), (y_pred-y)).mean()

def loss(y,y_pred):
    return ((y_pred-y)**2).mean()

alpha = 0.01
epochs=20

for ep in range(epochs):
    
    y_pred= forward(x,theta)
    l=loss(y,y_pred)
    dw=gradient(x,y,y_pred)
    theta=theta-(alpha*dw)
    
    print("theta = ", theta, "     loss = ", loss)
    

theta =  1.2      loss =  <function loss at 0x000000000279D700>
theta =  1.68      loss =  <function loss at 0x000000000279D700>
theta =  1.8719999999999999      loss =  <function loss at 0x000000000279D700>
theta =  1.9487999999999999      loss =  <function loss at 0x000000000279D700>
theta =  1.97952      loss =  <function loss at 0x000000000279D700>
theta =  1.991808      loss =  <function loss at 0x000000000279D700>
theta =  1.9967232      loss =  <function loss at 0x000000000279D700>
theta =  1.99868928      loss =  <function loss at 0x000000000279D700>
theta =  1.999475712      loss =  <function loss at 0x000000000279D700>
theta =  1.9997902848      loss =  <function loss at 0x000000000279D700>
theta =  1.99991611392      loss =  <function loss at 0x000000000279D700>
theta =  1.999966445568      loss =  <function loss at 0x000000000279D700>
theta =  1.9999865782272      loss =  <function loss at 0x000000000279D700>
theta =  1.99999463129088      loss =  <function loss at 0x000000

In [81]:
x=torch.tensor([1.0,2.0,3.0,4.0], dtype=torch.float32)
y=torch.tensor([2.0,4.0,6.0,8.0], dtype=torch.float32)

theta=torch.tensor(0.0, requires_grad= True)

#1 epoch=1 forward and 1 backward
def forward(x,theta):
    return theta*x

'''
def gradient(x,y,y_pred):
    return np.dot((2*x), (y_pred-y)).mean()
'''
def loss(y,y_pred):
    return ((y_pred-y)**2).mean()

alpha = 0.01
epochs=20

for ep in range(epochs):
    
    y_pred= forward(x,theta)
    l=loss(y,y_pred)
    l.backward()
    dw=theta.grad
    
    
    with torch.no_grad():
        theta=theta-(alpha*dw)
        
    theta.grad.zero_()
    
    print("theta = ", theta, "     loss = ", loss)
    

AttributeError: 'NoneType' object has no attribute 'zero_'